### ISSUE TITLE
content bounty

### ISSUE THREAD

**Issue by owocki** [econoar/ethhub#15]
hey @sassal -- [we](https://gitcoin.co) are experimenting with using our product to do content bounties.     i've [done a couple in the past](https://gitcoin.co/profile/ethereumbook) but we dont have a ton of data points.

do you have any content that's stubbed out which you'd like to invite a gitcoin user to write?    i'm happy to fund the bounty, but i figured i'd ask first so i know what (if anything) would be of the highest strategic value for us to fund.

best,
kevin

**Comment by sassal** [comment]
Hey Kevin,

That would be a great idea. I'd have to formalize a list of topics that we're looking to get documented asap. I'll see what I can pull together and get back to you!

Thanks

**Comment by owocki** [comment]
lets just start with one as a trial and see how it goez :)

**Comment by sassal** [comment]
We'd really love to get some work done on running a node (https://github.com/econoar/ethhub/tree/master/using-ethereum/running-a-node).

Few starter questions in there but we'd like to see a condensed version of this: https://github.com/ethereumbook/ethereumbook/blob/develop/clients.asciidoc

Thanks!

**Comment by owocki** [comment]
taking the bounty over to https://github.com/econoar/ethhub/issues/17
